wildfly-extras/wildfly-cloud-tests

.github/workflows/wildfly-cloud-tests.yml

Requires https://github.com/wildfly/wildfly/pull/15536 to be merged

Build WildFy with -Dskip.preview

---

README.md
common/src/main/java/org/wildfly/test/cloud/common/annotation/processor/WildFlyDefaultsKubernetesAnnotationProcessor.java
tests/core/env-vars-override-model/Dockerfile
tests/core/env-vars-override-model/pom.xml
tests/core/mpconfig-sources/Dockerfile
tests/core/mpconfig-sources/pom.xml
tests/core/mpconfig-sources/src/main/cli-script/init.cli
tests/core/mpconfig-sources/src/main/docker/postconfigure.sh
tests/datasources/postgresql/Dockerfile
tests/datasources/postgresql/pom.xml
tests/manual/rhosak/Dockerfile
tests/manual/rhosak/README.md
tests/manual/rhosak/pom.xml
tests/manual/rhosak/src/main/cli-script/init.cli
tests/manual/rhosak/src/main/docker/postconfigure.sh
tests/microprofile/reactive-messaging/strimzi/Dockerfile
tests/microprofile/reactive-messaging/strimzi/pom.xml
tests/pom.xml

Automatic CLI scripts must be named src/main/cli-script/init.sh

Generate Dockerfiles and auto-include CLI scripts

---

README.md

Signed-off-by: Emmanuel Hugonnet <ehugonne@redhat.com>

Adding instructions for running with podman

---

pom.xml
tests/elytron-oidc-client/auto-registration/pom.xml

Resolves #27 
Note that this also updates the JSoup version to one the has a recent CVE resolved.

[Issue_27] Control jsoup dependencyManagement locally

---

README.md
common/src/main/java/org/wildfly/test/cloud/common/annotation/processor/WildFlyDefaultsAbstractAnnotationProcessor.java
common/src/main/java/org/wildfly/test/cloud/common/annotation/processor/WildFlyDefaultsKubernetesAnnotationProcessor.java
common/src/main/java/org/wildfly/test/cloud/common/annotation/processor/WildFlyDefaultsOpenshiftAnnotationProcessor.java
pom.xml
tests/datasources/postgresql/pom.xml
tests/datasources/postgresql/src/main/java/org/wildfly/test/cloud/microprofile/datasources/postgresql/PostgresTransactionalBean.java
tests/datasources/postgresql/src/main/resources/META-INF/persistence.xml
tests/datasources/postgresql/src/test/java/org/wildfly/test/cloud/microprofile/datasources/postgresql/PostgresDatasourceTestCaseIT.java

Upgrade feature-packs

---

common/src/main/java/org/wildfly/test/cloud/common/WildFlySerialization.java
pom.xml

Needed to work around https://github.com/dekorateio/dekorate/pull/1141 before it is merged.

Force the dekorate ObjectMappers to initialise Jackson Modules

---

common/src/main/java/org/wildfly/test/cloud/common/WildFlyCommonExtension.java
common/src/main/java/org/wildfly/test/cloud/common/WildFlySerialization.java
pom.xml

Upgrade dekorate to 3.4.0

---

pom.xml

[issue53] Upgrade Jackson to 2.14.2 and Dekorate to 3.4.1.

---

pom.xml

Release notes https://github.com/wildfly/wildfly-maven-plugin/discussions/330

Upgrade wildfly-maven-plugin to 4.1.0.Final

---

.github/dependabot.yml
.github/workflows/wildfly-cloud-tests.yml
pom.xml

Various dependency updates and introduce dependabot.

Dependency updates

---

images/pom.xml
tests/pom.xml

Basically skip doing mvn deploy for the images and tests modules and children

Make releasable

---

common/junit-extension/src/main/java/org/wildfly/test/cloud/common/TestHelper.java
images/micrometer/pom.xml
images/pom.xml
test-bom/pom.xml
tests/observability/micrometer/pom.xml
tests/observability/micrometer/src/main/java/org/wildfly/test/cloud/observability/micrometer/MicrometerApp.java
tests/observability/micrometer/src/main/java/org/wildfly/test/cloud/observability/micrometer/MicrometerEndpoint.java
tests/observability/micrometer/src/main/webapp/WEB-INF/beans.xml
tests/observability/micrometer/src/test/container/collector-config.yml
tests/observability/micrometer/src/test/container/opentelemetry-collector.yml
tests/observability/micrometer/src/test/container/service.yml
tests/observability/micrometer/src/test/java/org/wildfly/test/cloud/observability/micrometer/MicrometerIT.java
tests/observability/pom.xml
tests/pom.xml

Create new observability module for this and future related tests Add simple smoke test for Micrometer support
Add new WF image for Micrometer tests
Add helper method to TestHelper
Define k8s resources needed for test

[add_micrometer] Add cloud tests for Micrometer

---

images/opentelemetry/pom.xml
images/pom.xml
test-bom/pom.xml
tests/observability/opentelemetry/pom.xml
tests/observability/opentelemetry/src/main/java/org/wildfly/test/cloud/observability/opentelemetry/OpenTelemetryApp.java
tests/observability/opentelemetry/src/main/java/org/wildfly/test/cloud/observability/opentelemetry/OpenTelemetryEndpoint.java
tests/observability/opentelemetry/src/main/resources/META-INF/microprofile-config.properties
tests/observability/opentelemetry/src/main/webapp/WEB-INF/beans.xml
tests/observability/opentelemetry/src/test/container/collector-config.yml
tests/observability/opentelemetry/src/test/container/opentelemetry-collector.yml
tests/observability/opentelemetry/src/test/container/service.yml
tests/observability/opentelemetry/src/test/java/org/wildfly/test/cloud/observability/opentelemetry/OpenTelemetryIT.java
tests/observability/pom.xml

Create image
Update BOM
Create test app
Create integration test

[add_otel] Add OpenTelemetry tests

---

.github/workflows/wildfly-cloud-tests-callable.yml

[Issue_146] Use SE 17 for compiling WildFly

---

.github/workflows/wildfly-cloud-tests.yml
.github/workflows/wildfly-pull-request-runner.yml

[Issue_145] Test with SE 21 as well

---

.github/workflows/wildfly-cloud-tests-callable.yml

[Issue_180] Delete the wildfly directory after the build

---

.github/workflows/wildfly-cloud-tests-callable-old.yml
.github/workflows/wildfly-pull-request-runner-old.yml
.github/workflows/wildfly-pull-request-runner.yml

This will run in parallel with the old mechanism .
A later PR will update to remove the old mechanism

New pull request trigger and reporting mechanism

---

.github/scripts/build-docker-image.sh
.github/scripts/clean-docker.sh
.github/scripts/start-registry.sh
.github/workflows/wildfly-cloud-tests-callable.yml
common/bom/pom.xml
tests/clustering/web-clustering/pom.xml
tests/core/env-vars-override-model/pom.xml
tests/core/mpconfig-sources/pom.xml
tests/datasources/postgresql/pom.xml
tests/elytron-oidc-client/auto-registration/pom.xml
tests/framework/app/pom.xml
tests/framework/kubernetes/pom.xml
tests/framework/openshift/pom.xml
tests/microprofile/reactive-messaging/strimzi/pom.xml
tests/observability/micrometer/pom.xml
tests/observability/opentelemetry/pom.xml
tests/pom.xml

And build them on demand before each test.

Reduce disk space on CI by deleting Docker images after tests

---

.github/workflows/wildfly-cloud-tests.yml
.github/workflows/wildfly-pull-request-runner.yml

[Issue_220] Drop SE 11 Testing

---

common/bom/pom.xml
images/microprofile-reactive-messaging-amqp/pom.xml
images/pom.xml
pom.xml
test-bom/pom.xml
tests/microprofile/reactive-messaging/amqp/Dockerfile
tests/microprofile/reactive-messaging/amqp/pom.xml
tests/microprofile/reactive-messaging/amqp/src/main/java/org/wildfly/test/cloud/microprofile/reactive/messaging/amqp/ReactiveMessagingWithAmqpApp.java
tests/microprofile/reactive-messaging/amqp/src/main/java/org/wildfly/test/cloud/microprofile/reactive/messaging/amqp/ReactiveMessagingWithAmqpBean.java
tests/microprofile/reactive-messaging/amqp/src/main/java/org/wildfly/test/cloud/microprofile/reactive/messaging/amqp/ReactiveMessagingWithAmqpEndpoint.java
tests/microprofile/reactive-messaging/amqp/src/main/resources/META-INF/microprofile-config.properties
tests/microprofile/reactive-messaging/amqp/src/test/container/artemis.yml
tests/microprofile/reactive-messaging/amqp/src/test/java/org/wildfly/test/cloud/microprofile/reactive/messaging/amqp/ReactiveMessagingWithAmqpIT.java
tests/microprofile/reactive-messaging/amqp/src/webapp/WEB-INF/beans.xml

Needs https://github.com/wildfly/wildfly/pull/16281 before it can be merged

[WFLY-15405] Test for the MP Reactive Messaging AMQP Connnector
